name: Build

on:
  pull_request:
    branches: 
      - "main"
  push:
    branches:
      - "*"
    tags:
      - "v*"
      - "beta*"
      - "dev*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        npm run setup
        sudo apt install -y simutrans-makeobj
        wget https://github.com/128na/simutrans-image-merger/releases/download/v1.6.1/release-ubuntu-latest.zip
        unzip release-ubuntu-latest.zip
        rm release-ubuntu-latest.zip
        mv dist/simutrans-image-merger ./
    - name: Build pak
      run: npm run build 

    - name: add readme
      run: |
        cd dist
        mkdir src
        find ./ -type f ! -name 'rtx.pak' -exec mv {} src/ \;
        cp ../doc/readme.txt ./
        cp ../doc/thumb.png ./


    - name: Upload artifact
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v4
      with:
        name: "build"
        path: "dist"

    - name: Create ZIP file
      if: startsWith(github.ref, 'refs/tags/') == true
      run: |
        TAG_NAME=$( git describe --tags --abbrev=0 )
        cd dist
        zip -r "../rtx-$TAG_NAME.zip" ./*

    - name: Release
      if: startsWith(github.ref, 'refs/tags/') == true
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        prerelease: ${{ startsWith(github.ref, 'refs/tags/v') == false }}
        files: rtx-*.zip