name: Pylint

on:
  pull_request:
    branches: 
      - "main"
  push:
    branches:
      - "*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Black
      run: black .

    - name: Run Pylint
      run: pylint **/*.py

    - # commit only to core contributors who have repository access
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: "[pylint] black fixes"
          commit_author: "GitHub Action <actions@github.com>"
          commit_user_email: "action@github.com"