name: Pylint

on:
  pull_request:
    branches: 
      - "main"
  push:
    branches:
      - "*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Black
      run: black .

    - name: Run Pylint
      run: pylint **/*.py

    - name: Determine the branch name
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          BRANCH_NAME="${{ github.head_ref }}"
        else
          BRANCH_NAME=$(basename ${{ github.ref }})
        fi
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
    
    - name: Check for formatting changes
      run: |
        git diff --exit-code || (
          git config --global user.name "github-actions" &&
          git config --global user.email "github-actions@github.com" &&
          git add . &&
          git commit -m "Apply formatting changes" &&
          git push origin HEAD:$BRANCH_NAME
        )
    