name: Release

on:
  push:
    tags:
      - "v*"
      - "dev*"

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        npm run setup
        sudo apt install -y simutrans-makeobj
        wget https://github.com/128na/simutrans-image-merger/releases/download/v1.6.1/release-ubuntu-latest.zip
        unzip release-ubuntu-latest.zip
        rm release-ubuntu-latest.zip
        mv dist/simutrans-image-merger ./
    - name: Build pak
      run: npm run build 

    - name: add readme
      run: |
        cd dist
        mkdir src
        mv *.pak ./src/
        cp ../readme.txt ./


    - name: Create ZIP file
      run: |
        TAG_NAME=$( git describe --tags --abbrev=0 )
        cd dist
        zip -r "../rtx-$TAG_NAME.zip" ./*

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        prerelease: ${{ startsWith(github.ref, 'refs/tags/v') == false }}
        files: rtx-*.zip